/*spring:
  application:
    name: Frost Service
  datasource:
    url: jdbc:h2:mem:business-users
    username: sa
    password: password
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
  h2:
    console:
      enabled: true
      path: /h2-console